---
Title: Metro Manila LRT-Line 1
---
gitGraph
	commit id:"Fernando Poe Jr."
	commit id:"Balintawak"
	commit id:"Yamaha Monumento"
	commit id:"5th Avenue"
	commit id:"R. Papa"
	commit id:"Abad Santos"
	commit id:"Blumentritt"
	commit id:"Tayuman"
	commit id:"Bambang"
	commit id:"Doroteo Jose"
	commit id:"Carriedo"
	commit id:"Central Terminal"
	commit id:"United Nations"
	commit id:"Pedro Gil"
	commit id:"Quirino"
	commit id:"Vito Cruz"
	commit id:"Gil Puyat"
	commit id:"Libertad"
	commit id:"EDSA"
	commit id:"Baclaran"
	commit id:"Redemptionist-ASEANA"
	commit id:"MIA Road"
	commit id:"PITX"
	commit id:"Ninoy Aquino Avenue"
	commit id:"Dr. Santos"
